Fix issue with docker when running faults tests
Many faults tests fail when docker is the container runtime application
due to the following issue:
AttributeError: 'Container' object has no attribute '_client'

Second here is the no Config dict issue

Change-Id: I971eab9f0f921cfb3e0403973040c9ff7b58fb0c