Fix Octavia reboot amphora compute node test
Octavia reboot_amphora_compute_node test fails with
MismatchError: 0 != -1: Missing replies from -1 members.

This patch fixes the reboot_amphora_compute_node test by reducing
the requests_count.

When requests_count*members_count is bigger then 1, the LB will assign
traffic to other members when using RoundRobin algorithm, and
evaluation of the members balance might be interfered when only one
member is supposed to receive all traffic.

Change-Id: I719a9e6f6db6d147a54a9245cf3f870495b2e40d